# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Filter events within a series of data
#' @description The function loops through a vector and filters events whose
#' values exceed a given threshold within a given window.
#' @param x The vector to be filtered.
#' @param threshold The threshold. Filter rule applied is x(i) > threshold.
#' @param window The search window.
#' @return A 2-column matrix with start and end indices.
#' @export
fever <- function(x, threshold, window) {
    .Call(`_fever_fever`, x, threshold, window)
}

